pub const HTML: &str = r#"<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Luo Realm 管理后台</title>
<style>
:root{color-scheme:light;--bg:#f4f6f8;--panel:#fff;--line:#d9dee5;--text:#17202a;--muted:#68727d;--brand:#166534;--brand2:#14532d;--danger:#b42318;--warn:#9a6700;--shadow:0 1px 2px rgba(16,24,40,.06)}
*{box-sizing:border-box;letter-spacing:0}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 system-ui,"Microsoft YaHei",sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}.hidden{display:none!important}
.login{min-height:100vh;display:grid;place-items:center;padding:24px}.login-box{width:min(420px,100%);background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:28px;box-shadow:var(--shadow)}.brand{font-size:22px;font-weight:750}.sub{color:var(--muted);margin:4px 0 20px}
label{display:block;color:var(--muted);font-size:12px;margin:12px 0 5px}input,select,textarea{width:100%;border:1px solid #b9c1ca;border-radius:5px;background:#fff;color:var(--text);padding:8px 10px;min-height:38px}textarea{resize:vertical;min-height:80px}input:focus,select:focus,textarea:focus{outline:2px solid rgba(22,101,52,.18);border-color:var(--brand)}
.btn{border:1px solid var(--line);border-radius:5px;background:#fff;padding:8px 12px;color:var(--text)}.btn:hover{background:#f7f8f9}.btn.primary{background:var(--brand);border-color:var(--brand);color:#fff}.btn.primary:hover{background:var(--brand2)}.btn.danger{border-color:#f0b8b3;color:var(--danger)}.btn:disabled{opacity:.55;cursor:not-allowed}.wide{width:100%}.row{display:flex;gap:8px;align-items:end}.row>*{flex:1}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.error{color:var(--danger);min-height:21px;margin-top:10px}.notice{position:fixed;right:20px;bottom:20px;max-width:380px;background:#15221a;color:#fff;padding:11px 14px;border-radius:6px;box-shadow:0 8px 30px rgba(0,0,0,.2);z-index:20}
.app{display:grid;grid-template-columns:220px minmax(0,1fr);min-height:100vh}.sidebar{background:#17231c;color:#e7eee9;padding:18px 12px;position:sticky;top:0;height:100vh}.sidebar .brand{padding:0 10px 18px;border-bottom:1px solid #344139}.nav{display:grid;gap:4px;margin-top:14px}.nav button{border:0;background:transparent;color:#cdd7d0;text-align:left;padding:9px 10px;border-radius:5px}.nav button:hover,.nav button.active{background:#2b3d31;color:#fff}.sidebar-foot{position:absolute;bottom:16px;left:12px;right:12px;color:#9fb0a4;font-size:12px}.main{min-width:0}.topbar{height:58px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px;position:sticky;top:0;z-index:5}.status{display:flex;align-items:center;gap:7px;color:var(--muted)}.dot{width:8px;height:8px;border-radius:50%;background:#20a05a}.content{max-width:1400px;padding:24px}.page{display:none}.page.active{display:block}h1{font-size:20px;margin:0 0 4px}h2{font-size:15px;margin:0 0 12px}.desc{color:var(--muted);margin:0 0 20px}.section{background:var(--panel);border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:18px;margin:0 0 18px;box-shadow:var(--shadow)}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.stat{background:#fff;border:1px solid var(--line);border-radius:6px;padding:16px}.stat strong{display:block;font-size:25px}.stat span{color:var(--muted)}
.toolbar{display:flex;gap:8px;align-items:end;margin-bottom:12px}.toolbar .grow{flex:1}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:5px}table{border-collapse:collapse;width:100%;min-width:720px;background:#fff}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #e9edf1;vertical-align:middle}th{font-size:12px;color:var(--muted);background:#f8f9fa}tr:last-child td{border-bottom:0}.switch{width:18px;height:18px;min-height:0}.empty{padding:30px;text-align:center;color:var(--muted)}
.split{display:grid;grid-template-columns:minmax(320px,42%) minmax(420px,1fr);gap:18px}.panel{background:#fff;border:1px solid var(--line);border-radius:6px;padding:16px}.tabs{display:flex;gap:2px;border-bottom:1px solid var(--line);margin-bottom:14px}.tabs button{border:0;background:transparent;padding:9px 12px;color:var(--muted);border-bottom:2px solid transparent}.tabs button.active{color:var(--brand);border-color:var(--brand)}.tab-body{display:none}.tab-body.active{display:block}.muted{color:var(--muted)}.code{font-family:ui-monospace,Consolas,monospace}.danger-zone{border-left:3px solid var(--danger)}
@media(max-width:900px){.app{grid-template-columns:1fr}.sidebar{height:auto;position:static}.nav{grid-template-columns:repeat(5,1fr)}.nav button{text-align:center;padding:8px 3px}.sidebar-foot{display:none}.topbar{position:static;padding:0 16px}.content{padding:16px}.stats{grid-template-columns:repeat(2,1fr)}.split{grid-template-columns:1fr}}
@media(max-width:520px){.nav{grid-template-columns:repeat(3,1fr)}.stats{grid-template-columns:1fr}.row,.toolbar{align-items:stretch;flex-direction:column}.content{padding:12px}.section{margin-left:-12px;margin-right:-12px}.topbar span:first-child{max-width:170px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
</style>
</head>
<body>
<main id="login" class="login"><form id="loginForm" class="login-box"><div class="brand">Luo Realm</div><p class="sub">管理后台</p><label for="token">管理 Token</label><input id="token" type="password" autocomplete="current-password" required minlength="32"><button class="btn primary wide" type="submit" style="margin-top:14px">登录</button><div id="loginError" class="error"></div></form></main>
<div id="app" class="app hidden"><aside class="sidebar"><div class="brand">LR 管理后台</div><nav class="nav"><button data-page="dashboard" class="active">仪表盘</button><button data-page="groups">群管理</button><button data-page="players">玩家管理</button><button data-page="config">运行配置</button><button data-page="operations">运维审计</button></nav><div class="sidebar-foot">仅建议在受信局域网访问</div></aside><div class="main"><header class="topbar"><span id="pageTitle">仪表盘</span><div class="status"><span class="dot"></span><span id="serverStatus">连接正常</span><button id="logout" class="btn">退出</button></div></header><div class="content">
<section id="dashboard" class="page active"><h1>运行概览</h1><p class="desc">当前世界状态与数据健康概览</p><div id="stats" class="stats"></div><div class="section"><h2>安全状态</h2><p>群聊采用显式白名单，未登记群默认关闭。私聊仅配置中的管理员 QQ 可用。</p><p class="muted">后台使用 HTTP。跨公网访问时必须置于 HTTPS 反向代理之后。</p></div></section>
<section id="groups" class="page"><h1>群管理</h1><p class="desc">启用指定群，并按群控制通用、事件和战斗功能</p><div class="section"><div class="toolbar"><div class="grow"><label for="groupSearch">群号搜索</label><input id="groupSearch" placeholder="输入群号"></div><button id="groupSearchButton" class="btn">查询</button><button id="groupAddButton" class="btn primary">新增群</button></div><div class="table-wrap"><table><thead><tr><th>群号</th><th>总开关</th><th>通用</th><th>事件</th><th>战斗</th><th>更新时间</th><th>操作</th></tr></thead><tbody id="groupRows"></tbody></table></div></div></section>
<section id="players" class="page"><h1>玩家管理</h1><p class="desc">查询和修正玩家资料、钱包、修行、物品与统计</p><div class="split"><div class="panel"><div class="toolbar"><div class="grow"><label for="playerSearch">QQ 或名称</label><input id="playerSearch"></div><button id="playerSearchButton" class="btn">查询</button></div><div class="table-wrap"><table style="min-width:480px"><thead><tr><th>QQ</th><th>名称</th><th>体系 / 境界</th><th></th></tr></thead><tbody id="playerRows"></tbody></table></div></div><div id="playerDetail" class="panel"><div class="empty">从左侧选择玩家</div></div></div></section>
<section id="config" class="page"><h1>运行配置</h1><p class="desc">修改后立即更新消息访问策略；监听地址和端口需重启插件后生效</p><form id="configForm" class="section"><div class="row"><div><label for="prefixEnabled">命令模式</label><select id="prefixEnabled"><option value="false">默认无前缀</option><option value="true">强制前缀</option></select></div><div><label for="prefix">命令前缀</label><input id="prefix" maxlength="32"></div></div><label for="adminIds">允许私聊的管理员 QQ（每行一个）</label><textarea id="adminIds"></textarea><div class="row"><div><label for="bind">监听地址</label><input id="bind"></div><div><label for="port">起始端口</label><input id="port" type="number" min="1" max="65526"></div></div><div class="actions"><button class="btn primary" type="submit">保存配置</button></div></form><div class="section"><h2>修行体系定义</h2><div id="systems"></div></div></section>
<section id="operations" class="page"><h1>运维审计</h1><p class="desc">在线备份、操作记录和管理 Token 轮换</p><div class="section"><h2>在线备份</h2><div class="row"><div><label for="backupReason">备份原因</label><input id="backupReason" value="例行安全备份"></div><button id="backupButton" class="btn primary">创建备份</button></div></div><div class="section danger-zone"><h2>轮换管理 Token</h2><label for="newToken">新 Token（至少 32 字符）</label><input id="newToken" type="password"><label for="tokenReason">轮换原因</label><input id="tokenReason" value="定期安全轮换"><div class="actions"><button id="generateToken" class="btn">本地生成</button><button id="rotateToken" class="btn danger">确认轮换</button></div></div><div class="section"><h2>最近操作</h2><div class="table-wrap"><table><thead><tr><th>时间</th><th>操作</th><th>目标</th><th>原因</th><th>结果</th></tr></thead><tbody id="auditRows"></tbody></table></div></div></section>
</div></div></div><div id="notice" class="notice hidden"></div>
<script>
'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('lr_admin_token')||'';let currentPlayer=null,runtimeConfig=null;
function showNotice(message,bad=false){const node=$('notice');node.textContent=message;node.style.background=bad?'#8f1d18':'#15221a';node.classList.remove('hidden');setTimeout(()=>node.classList.add('hidden'),3500)}
async function api(path,options={}){const headers={'Authorization':'Bearer '+token};if(options.body)headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});const payload=await response.json().catch(()=>({ok:false,error:{message:'响应格式错误'}}));if(!response.ok||!payload.ok)throw new Error(payload.error?.message||'请求失败');return payload.data}
function cell(row,text){const td=document.createElement('td');td.textContent=String(text??'');row.appendChild(td);return td}
function button(text,handler,kind='btn'){const node=document.createElement('button');node.className=kind;node.textContent=text;node.addEventListener('click',handler);return node}
function reason(promptText='请输入修改原因'){const value=prompt(promptText,'后台人工调整');return value&&value.trim().length>=2?value.trim():null}
async function loadDashboard(){const data=await api('/api/overview');const labels=[['玩家',data.players],['完整角色',data.active_players],['待选体系',data.pending_players],['启用群',data.enabled_groups],['战斗记录',data.combats],['钱包流水',data.wallet_transactions]];const root=$('stats');root.replaceChildren();labels.forEach(([label,value])=>{const box=document.createElement('div');box.className='stat';const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;box.append(strong,span);root.appendChild(box)})}
async function loadGroups(){const data=await api('/api/groups?search='+encodeURIComponent($('groupSearch').value));const root=$('groupRows');root.replaceChildren();data.items.forEach(group=>{const row=document.createElement('tr');cell(row,group.group_id);[['enabled','总开关'],['general','通用'],['event','事件'],['combat','战斗']].forEach(([key,label])=>{const td=cell(row,'');const input=document.createElement('input');input.type='checkbox';input.className='switch';input.checked=group[key];input.dataset.key=key;input.title=label;td.appendChild(input)});cell(row,new Date(group.updated_at*1000).toLocaleString());const action=cell(row,'');action.appendChild(button('保存',async()=>{const inputs=[...row.querySelectorAll('input')];const values=Object.fromEntries(inputs.map(input=>[input.dataset.key,input.checked]));const why=reason();if(!why)return;try{if(values.enabled!==group.enabled){const payload={enabled:values.enabled,reason:why};if(!values.enabled){const summary=`group:${group.group_id}:disable`;if(!confirm(`确认停用群 ${group.group_id}？`))return;payload.confirm=summary}await api('/api/groups/'+group.group_id,{method:'PUT',body:JSON.stringify(payload)})}await api('/api/groups/'+group.group_id+'/features',{method:'PUT',body:JSON.stringify({...values,reason:why})});showNotice('群配置已保存');loadGroups()}catch(error){showNotice(error.message,true)}}));root.appendChild(row)})}
async function addGroup(){const id=prompt('输入要登记的群号');if(!id||!/^\d+$/.test(id))return;const why=reason('请输入启用该群的原因');if(!why)return;try{await api('/api/groups',{method:'POST',body:JSON.stringify({group_id:Number(id),enabled:true,reason:why})});showNotice('群已启用');loadGroups()}catch(error){showNotice(error.message,true)}}
async function loadPlayers(){const data=await api('/api/players?search='+encodeURIComponent($('playerSearch').value));const root=$('playerRows');root.replaceChildren();data.items.forEach(player=>{const row=document.createElement('tr');cell(row,player.player_id);cell(row,player.display_name);cell(row,player.registration_state==='pending_system'?'待选体系':`${player.system_id} / ${player.realm_index+1}`);cell(row,'').appendChild(button('管理',()=>loadPlayer(player.player_id)));root.appendChild(row)})}
function field(label,id,value,type='text'){const wrap=document.createElement('div');const lab=document.createElement('label');lab.htmlFor=id;lab.textContent=label;const input=document.createElement('input');input.id=id;input.type=type;input.value=value??'';wrap.append(lab,input);return wrap}
async function loadPlayer(id){const data=await api('/api/players/'+id);currentPlayer=data;renderPlayer(data)}
function renderPlayer(data){const root=$('playerDetail');root.replaceChildren();const title=document.createElement('h2');title.textContent=`${data.player.display_name} · ${data.player.player_id} · ${data.player.registration_state==='active'?'完整角色':'待选体系'}`;root.appendChild(title);const tabs=document.createElement('div');tabs.className='tabs';const bodies=document.createElement('div');const definitions=[['资料','profile'],['钱包','wallet'],['修行','cultivation'],['物品','items'],['统计','statistics']];definitions.forEach(([label,key],index)=>{const tab=button(label,()=>selectPlayerTab(key),'');tab.dataset.tab=key;if(index===0)tab.classList.add('active');tabs.appendChild(tab);const body=document.createElement('div');body.id='player-'+key;body.className='tab-body'+(index===0?' active':'');bodies.appendChild(body)});root.append(tabs,bodies);renderProfile(data);renderWallet(data);renderCultivation(data);renderItems(data);renderStatistics(data)}
function selectPlayerTab(key){document.querySelectorAll('#playerDetail [data-tab]').forEach(node=>node.classList.toggle('active',node.dataset.tab===key));document.querySelectorAll('#playerDetail .tab-body').forEach(node=>node.classList.toggle('active',node.id==='player-'+key))}
function renderProfile(data){const root=$('player-profile');const name=field('显示名称','editName',data.player.display_name);const status=document.createElement('select');status.id='editStatus';['active','disabled','deleted'].forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=value===data.player.status;status.appendChild(option)});const label=document.createElement('label');label.textContent='状态';root.append(name,label,status,button('保存资料',()=>saveProfile(data.player.player_id),'btn primary'))}
async function saveProfile(id){const why=reason();if(!why)return;const status=$('editStatus').value,payload={display_name:$('editName').value,status,reason:why};if(status!=='active'){if(!confirm(`确认将玩家 ${id} 状态改为 ${status}？`))return;payload.confirm=`player:${id}:${status}`}try{await api(`/api/players/${id}/profile`,{method:'PUT',body:JSON.stringify(payload)});showNotice('资料已保存');loadPlayer(id)}catch(error){showNotice(error.message,true)}}
function renderWallet(data){const root=$('player-wallet');const info=document.createElement('p');info.textContent=`金币 ${data.player.coins} · 刻印 ${data.player.marks}`;const currency=document.createElement('select');currency.id='walletCurrency';[['coins','金币'],['marks','刻印']].forEach(([value,text])=>{const option=document.createElement('option');option.value=value;option.textContent=text;currency.appendChild(option)});const amount=field('变化量（负数为扣除）','walletDelta',0,'number');const label=document.createElement('label');label.textContent='货币';const action=button('调整钱包',()=>saveWallet(data.player.player_id),'btn primary');action.disabled=data.player.registration_state!=='active';root.append(info,label,currency,amount,action)}
async function saveWallet(id){const delta=Number($('walletDelta').value);const currency=$('walletCurrency').value;const why=reason();if(!why||!delta)return;const payload={currency,delta,reason:why};if(delta<0||Math.abs(delta)>=10000){if(!confirm(`确认调整 ${currency} ${delta}？`))return;payload.confirm=`wallet:${id}:${currency}:${delta}`}try{await api(`/api/players/${id}/wallet`,{method:'POST',body:JSON.stringify(payload)});showNotice('钱包已调整');loadPlayer(id)}catch(error){showNotice(error.message,true)}}
function renderCultivation(data){const root=$('player-cultivation');if(data.player.registration_state==='pending_system'){const note=document.createElement('p');note.className='muted';note.textContent='保存有效体系后将完成角色注册。';root.appendChild(note)}root.append(field('体系标识','cultSystem',data.player.system_id??''),field('境界索引（从 0 开始）','cultRealm',data.player.realm_index??0,'number'),field('修行进度','cultProgress',data.player.progress??0,'number'),button('保存修行状态',()=>saveCultivation(data.player.player_id),'btn primary'))}
async function saveCultivation(id){const system_id=$('cultSystem').value.trim(),realm_index=Number($('cultRealm').value),progress=Number($('cultProgress').value),why=reason();if(!why)return;const summary=`cultivation:${id}:${system_id}:${realm_index}:${progress}`;if(!confirm(`确认修改玩家 ${id} 的修行状态？`))return;try{await api(`/api/players/${id}/cultivation`,{method:'PUT',body:JSON.stringify({system_id,realm_index,progress,reason:why,confirm:summary})});showNotice('修行状态已保存');loadPlayer(id)}catch(error){showNotice(error.message,true)}}
function renderItems(data){const root=$('player-items');const pending=data.player.registration_state!=='active';const table=document.createElement('table');table.style.minWidth='0';data.items.forEach(item=>{const row=document.createElement('tr');cell(row,`${item.definition_id} × ${item.quantity}`);cell(row,item.quality);const action=cell(row,''),remove=button('删除',()=>deleteItem(data.player.player_id,item.item_instance_id),'btn danger');remove.disabled=pending;action.appendChild(remove);table.appendChild(row)});const grant=button('发放物品',()=>grantItem(data.player.player_id),'btn primary');grant.disabled=pending;root.append(table,field('物品定义 ID','itemDefinition',''),field('数量','itemQuantity',1,'number'),field('品质','itemQuality','common'),grant)}
async function grantItem(id){const why=reason();if(!why)return;try{await api(`/api/players/${id}/items`,{method:'POST',body:JSON.stringify({definition_id:$('itemDefinition').value,quantity:Number($('itemQuantity').value),quality:$('itemQuality').value,reason:why})});showNotice('物品已发放');loadPlayer(id)}catch(error){showNotice(error.message,true)}}
async function deleteItem(id,itemId){const why=reason();if(!why||!confirm(`确认删除物品实例 ${itemId}？`))return;try{await api(`/api/players/${id}/items/${itemId}`,{method:'DELETE',body:JSON.stringify({reason:why,confirm:`item:${id}:${itemId}:remove`})});showNotice('物品已删除');loadPlayer(id)}catch(error){showNotice(error.message,true)}}
function renderStatistics(data){const root=$('player-statistics');data.statistics.forEach(stat=>{const p=document.createElement('p');p.textContent=`${stat.metric_code}: ${stat.metric_value}`;root.appendChild(p)});const action=button('保存统计',()=>saveStatistic(data.player.player_id),'btn primary');action.disabled=data.player.registration_state!=='active';root.append(field('统计标识','statMetric','wins'),field('数值','statValue',0,'number'),action)}
async function saveStatistic(id){const why=reason();if(!why)return;const metric=$('statMetric').value,value=Number($('statValue').value),summary=`statistic:${id}:${metric}:${value}`;if(!confirm(`确认将 ${metric} 修正为 ${value}？`))return;try{await api(`/api/players/${id}/statistics`,{method:'PUT',body:JSON.stringify({metric,value,reason:why,confirm:summary})});showNotice('统计已保存');loadPlayer(id)}catch(error){showNotice(error.message,true)}}
async function loadConfig(){const data=await api('/api/config');runtimeConfig=data;$('prefixEnabled').value=String(data.command.prefix_enabled);$('prefix').value=data.command.prefix;$('adminIds').value=data.admin.admin_ids.join('\n');$('bind').value=data.admin.bind;$('port').value=data.admin.port;const systems=await api('/api/definitions/cultivation');const root=$('systems');root.replaceChildren();systems.forEach(system=>{const p=document.createElement('p');const strong=document.createElement('strong');strong.textContent=`${system.name} (${system.id})`;const span=document.createElement('span');span.className='muted';span.textContent=` · ${system.realms.map(realm=>realm.name).join(' → ')}`;p.append(strong,span);root.appendChild(p)})}
async function saveConfig(event){event.preventDefault();const why=reason('请输入运行配置修改原因');if(!why||!confirm('确认修改命令、管理员与后台监听配置？'))return;const admin_ids=$('adminIds').value.split(/\s+/).filter(Boolean).map(Number).filter(Number.isSafeInteger);const payload={command:{prefix_enabled:$('prefixEnabled').value==='true',prefix:$('prefix').value},admin:{enabled:runtimeConfig?.admin.enabled??true,bind:$('bind').value,port:Number($('port').value),admin_ids},reason:why,confirm:'config:update'};try{runtimeConfig=await api('/api/config',{method:'PUT',body:JSON.stringify(payload)});showNotice('配置已保存')}catch(error){showNotice(error.message,true)}}
async function loadAudit(){const data=await api('/api/audit?limit=100');const root=$('auditRows');root.replaceChildren();data.items.forEach(item=>{const row=document.createElement('tr');cell(row,new Date(item.created_at*1000).toLocaleString());cell(row,item.action_code);cell(row,`${item.target_type}:${item.target_id}`);cell(row,item.reason);cell(row,item.result);root.appendChild(row)})}
async function backup(){try{const data=await api('/api/backup',{method:'POST',body:JSON.stringify({reason:$('backupReason').value})});showNotice('备份已创建：'+data.file);loadAudit()}catch(error){showNotice(error.message,true)}}
function generateToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);$('newToken').value=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');showNotice('新 Token 已在当前浏览器本地生成')}
async function rotateToken(){const next=$('newToken').value,why=$('tokenReason').value;if(!confirm('轮换后旧 Token 将立即失效，确认继续？'))return;try{await api('/api/token/rotate',{method:'POST',body:JSON.stringify({token:next,reason:why,confirm:'token:rotate'})});token=next;sessionStorage.setItem('lr_admin_token',token);$('newToken').value='';showNotice('Token 已轮换')}catch(error){showNotice(error.message,true)}}
async function openPage(name){document.querySelectorAll('.page').forEach(node=>node.classList.toggle('active',node.id===name));document.querySelectorAll('.nav button').forEach(node=>node.classList.toggle('active',node.dataset.page===name));const titles={dashboard:'仪表盘',groups:'群管理',players:'玩家管理',config:'运行配置',operations:'运维审计'};$('pageTitle').textContent=titles[name];try{if(name==='dashboard')await loadDashboard();if(name==='groups')await loadGroups();if(name==='players')await loadPlayers();if(name==='config')await loadConfig();if(name==='operations')await loadAudit()}catch(error){showNotice(error.message,true)}}
async function authenticate(candidate){const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:candidate})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error?.message||'登录失败');token=candidate;sessionStorage.setItem('lr_admin_token',token);$('login').classList.add('hidden');$('app').classList.remove('hidden');openPage('dashboard')}
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();$('loginError').textContent='';try{await authenticate($('token').value)}catch(error){$('loginError').textContent=error.message}});document.querySelectorAll('.nav button').forEach(node=>node.addEventListener('click',()=>openPage(node.dataset.page)));$('logout').addEventListener('click',()=>{sessionStorage.removeItem('lr_admin_token');location.reload()});$('groupSearchButton').addEventListener('click',loadGroups);$('groupAddButton').addEventListener('click',addGroup);$('playerSearchButton').addEventListener('click',loadPlayers);$('configForm').addEventListener('submit',saveConfig);$('backupButton').addEventListener('click',backup);$('generateToken').addEventListener('click',generateToken);$('rotateToken').addEventListener('click',rotateToken);if(token)authenticate(token).catch(()=>sessionStorage.removeItem('lr_admin_token'));
</script>
</body></html>"#;
